### ISSUE TITLE
Support configuration based caching profiles

### ISSUE THREAD

**Issue by liddellj** [openrasta/openrasta-caching#3]
Our organisation has a need to vary the cache settings per environment, so we need to be able to define max age in web/app.config instead of hard-coding it.

We have implemented a quick solution to this by adding a 'Profile' property to AbstractCacheAttribute, and picking it up within CacheResponse and pulling out the Duration from config. For quickness, the configuration side of things uses the existing System.Web OutputCacheSettingsSection - however, this results in a dependency on System.Web and System.Configuration - which I guess you would not be keen to pull into core. I have pushed these changes to https://github.com/liddellj/openrasta-caching if you are interested. If you would be comfortable with these dependencies then let me know and I can issue a pull request.

It would be useful for us if this feature were to be baked into the core library, but I imagine this would require that the extra dependencies be removed. If I get the time I may take a run at this myself - if I do I will issue a pull request.

**Comment by serialseb** [comment]
Hey,

it's on the task list, and is simply to add the MaxAge on the Map configuration API the same way we do it for LastModified, you're then free to go read it from system.web.cache if need be.

We could read the default values in the asp.net hosts and read them back in the caching module if needed, that'd be useful.

**Comment by liddellj** [comment]
Just doing some housekeeping on my GitHub issues and found this. I'm going to close this as we no longer use OpenRasta. Feel free to reopen if you want to keep tracking it anyway.

**Comment by holytshirt** [comment]
Thanks @liddellj

**Comment by serialseb** [comment]
Ah well. Maybe see you around in the future :)

**Comment by liddellj** [comment]
👍
